import {scryptSync} from 'node:crypto';import {db,id,migrate,now} from './db.ts';
export function seed(){migrate();const created=now();const hash=scryptSync('demo1234','chorequest-demo',64).toString('hex');
db.transaction(()=>{for(const table of ['user_achievements','achievements','preferences','activity_logs','notifications','redemptions','reward_goals','rewards','daily_activity','xp_transactions','point_transactions','decisions','submissions','assignments','chores','memberships','families','sessions','users'])db.prepare(`DELETE FROM ${table}`).run();
const users=[['parent-demo','jamie@chorequest.demo','Jamie Morgan','parent'],['student-alex','alex@chorequest.demo','Alex Morgan','student'],['student-sam','sam@chorequest.demo','Sam Morgan','student']] as const;for(const [uid,email,name] of users)db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(uid,email,hash,name,'America/New_York',created);
db.prepare('INSERT INTO families VALUES(?,?,?,?,?)').run('family-demo','Morgan Family','parent-demo','{}',created);for(const [uid,,,role] of users)db.prepare('INSERT INTO memberships VALUES(?,?,?,?,?)').run(id(),'family-demo',uid,role,'active');
for(const [uid,theme] of [['parent-demo','garden'],['student-alex','garden'],['student-sam','ocean']])db.prepare('INSERT INTO preferences VALUES(?,?,?,?,?)').run(uid,theme,1,0,1);
const chores=[['make-bed','Make your bed','Straighten sheets and fluff pillows.','bedroom','easy',15,20,'daily',0,0],['dishwasher','Empty the dishwasher','Put away clean dishes before dinner.','kitchen','medium',30,45,'daily',1,1],['math','Finish math homework','Complete problems 1–20.','school','hard',40,70,'none',1,0],['recycling','Take out recycling','Sort paper and carry the bin outside.','outdoors','easy',20,30,'weekly',0,0],['feed-pet','Feed Pepper','Fresh water and one scoop of food.','pets','easy',15,20,'daily',1,0]] as const;
for(const c of chores)db.prepare('INSERT INTO chores VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c[0],'family-demo','parent-demo',c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8],c[9],null,created);
const due=(days:number,hour:number)=>{const d=new Date();d.setDate(d.getDate()+days);d.setHours(hour,0,0,0);return d.toISOString()};
const assignments=[['a-bed','make-bed','student-alex',due(0,9),'todo'],['a-dish','dishwasher','student-alex',due(0,17),'pending'],['a-math','math','student-alex',due(1,19),'changes_requested'],['a-recycle','recycling','student-alex',due(-1,18),'completed'],['s-pet','feed-pet','student-sam',due(0,8),'todo'],['s-bed','make-bed','student-sam',due(0,9),'completed']] as const;for(const a of assignments)db.prepare('INSERT INTO assignments VALUES(?,?,?,?,?,?,?)').run(...a,null,created);
db.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?,?)').run('sub-dish','a-dish',1,'All dishes put away.','https://images.example/proof.jpg','pending',created);db.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?,?)').run('sub-math','a-math',1,'Finished! ',null,'changes_requested',created);db.prepare('INSERT INTO decisions VALUES(?,?,?,?,?,?,?)').run(id(),'sub-math','parent-demo','changes_requested','Please check question 12.',null,created);
for(const row of [[300,'welcome','Starter points','welcome:alex'],[440,'chore','Chores completed this month','history:alex'],[-50,'reward','Sticker pack','reward:old']] as const)db.prepare('INSERT INTO point_transactions VALUES(?,?,?,?,?,?,?,?,?)').run(id(),'family-demo','student-alex',row[0],row[1],row[2],null,row[3],created);
db.prepare('INSERT INTO xp_transactions VALUES(?,?,?,?,?,?,?,?)').run(id(),'family-demo','student-alex',520,'chore',null,'xp:history',created);
for(let i=0;i<5;i++){const d=new Date();d.setDate(d.getDate()-i);const local=d.toLocaleDateString('en-CA',{timeZone:'America/New_York'});db.prepare('INSERT INTO daily_activity VALUES(?,?,?,?,?)').run(id(),'student-alex',local,'America/New_York',1)}
const rewards=[['movie','Movie night pick','Choose Friday’s family movie.','🎬',1000,5,1,1],['dessert','Choose dessert','Pick this weekend’s dessert.','🧁',350,3,1,0],['later-bed','30 minutes later bedtime','One weekend night.','🌙',600,2,1,1],['park','Adventure park trip','A family afternoon adventure.','🎢',1800,1,1,1]] as const;for(const r of rewards)db.prepare('INSERT INTO rewards VALUES(?,?,?,?,?,?,?,?,?,?)').run(r[0],'family-demo',...r.slice(1),created);db.prepare('INSERT INTO reward_goals VALUES(?,?,?,?,?)').run(id(),'student-alex','movie',1,created);
for(const [user,title,body] of [['parent-demo','Chore ready to review','Alex submitted Empty the dishwasher.'],['student-alex','Nice streak!','You have completed a chore five days in a row.'],['student-alex','Changes requested','Jamie left feedback on math homework.']] as const)db.prepare('INSERT INTO notifications VALUES(?,?,?,?,?,?)').run(id(),user,title,body,null,created);
for(const [actor,action,message,amount] of [['student-alex','submission','Alex submitted Empty the dishwasher',null],['parent-demo','chore.created','Jamie assigned Feed Pepper',null],['student-alex','chore.completed','Alex completed Take out recycling',20]] as const)db.prepare('INSERT INTO activity_logs VALUES(?,?,?,?,?,?,?)').run(id(),'family-demo',actor,action,message,amount,created);
for(const a of [['first','First Steps','Complete your first chore','🌱',1],['combo','Consistency Combo','Complete chores five days running','🔥',5],['helper','House Hero','Complete twenty chores','🏆',20]] as const)db.prepare('INSERT INTO achievements VALUES(?,?,?,?,?)').run(...a);db.prepare('INSERT INTO user_achievements VALUES(?,?,?)').run('student-alex','first',created);db.prepare('INSERT INTO user_achievements VALUES(?,?,?)').run('student-alex','combo',created);
})();}
if(import.meta.url===`file://${process.argv[1].replaceAll('\\','/')}`){seed();console.log('Demo family seeded.');}
