import{afterAll,beforeAll,beforeEach,describe,expect,it}from'vitest';import type{Server}from'node:http';
process.env.NODE_ENV='test';process.env.DATABASE_PATH=':memory:';
let server:Server,base='';let seed:()=>void;
beforeAll(async()=>{const app=(await import('../src/server/app.ts')).default;seed=(await import('../src/server/seed.ts')).seed;await new Promise<void>(resolve=>{server=app.listen(0,()=>{const address=server.address();if(typeof address==='object'&&address)base=`http://127.0.0.1:${address.port}`;resolve()})})});beforeEach(()=>seed());afterAll(()=>new Promise<void>(resolve=>server.close(()=>resolve())));
async function request(path:string,user:string,init:RequestInit={}){return fetch(`${base}/api${path}`,{...init,headers:{'Content-Type':'application/json','x-demo-user':user,...init.headers}})}
async function dashboard(user='student-alex'){const response=await request('/dashboard',user);return(await response.json()).data}
describe('chore approval ledger',()=>{it('keeps pending work unawarded and awards approval exactly once',async()=>{expect((await dashboard()).user.points).toBe(690);const first=await request('/parent/submissions/sub-dish/decision','parent-demo',{method:'POST',body:JSON.stringify({decision:'approved',note:''})});expect(first.status).toBe(200);expect((await dashboard()).user.points).toBe(720);const repeat=await request('/parent/submissions/sub-dish/decision','parent-demo',{method:'POST',body:JSON.stringify({decision:'approved',note:''})});expect(repeat.status).toBe(409);expect((await dashboard()).user.points).toBe(720)});it('does not award rejected work and preserves feedback for resubmission',async()=>{const rejected=await request('/parent/submissions/sub-dish/decision','parent-demo',{method:'POST',body:JSON.stringify({decision:'rejected',note:'Please dry the cups.'})});expect(rejected.status).toBe(200);expect((await dashboard()).user.points).toBe(690);const resubmit=await request('/student/assignments/a-dish/submit','student-alex',{method:'POST',body:JSON.stringify({note:'Fixed it.','proofUrl':'https://example.com/proof.jpg'})});expect(resubmit.status).toBe(201);expect((await dashboard()).chores.find((c:{id:string})=>c.id==='a-dish').status).toBe('pending')})});
describe('server authorization',()=>{it('blocks students from parent mutations',async()=>{const response=await request('/parent/chores','student-alex',{method:'POST',body:'{}'});expect(response.status).toBe(403)});it('does not expose another family assignment through student IDs',async()=>{const response=await request('/student/assignments/s-pet/submit','student-alex',{method:'POST',body:JSON.stringify({note:''})});expect(response.status).toBe(404)})});
describe('reward redemption ledger',()=>{it('deducts once, treats repeat keys idempotently, and prevents negative balance',async()=>{const headers={'Idempotency-Key':'test-redemption'};const first=await request('/student/rewards/dessert/redeem','student-alex',{method:'POST',headers});expect(first.status).toBe(201);expect((await dashboard()).user.points).toBe(340);const repeat=await request('/student/rewards/dessert/redeem','student-alex',{method:'POST',headers});expect(repeat.status).toBe(200);expect((await dashboard()).user.points).toBe(340);const expensive=await request('/student/rewards/park/redeem','student-alex',{method:'POST',headers:{'Idempotency-Key':'too-expensive'}});expect(expensive.status).toBe(409);expect((await dashboard()).user.points).toBe(340)})});
